### ISSUE TITLE
HTML rendering of task markers

### ISSUE THREAD

**Issue by smondet** [dbuenzli/cmarkit#15]
In [`/src/cmarkit_html.ml:340`](https://github.com/dbuenzli/cmarkit/blob/5720ff2d05376192833570623f607cb3b6c7b5a5/src/cmarkit_html.ml#L340-L355)

```ocaml
let close = match Block.List_item.task_status_of_task_marker mark with
| `Unchecked ->
    C.string c
      "<div class=\"task\"><input type=\"checkbox\" disabled><div>";
    "</div></div></li>\n"
| `Checked | `Other _ ->
    C.string c
      "<div class=\"task\"><input type=\"checkbox\" disabled checked><div>";
    "</div></div></li>\n"
| `Cancelled ->
    C.string c
      "<div class=\"task\"><input type=\"checkbox\" disabled><del>";
    "<del></div></li>\n"
```

In the `` `Cancelled`` case after the input we have `<del>` which is an “inline”
element while the other cases we have another `<div>` (which requires some CSS
magic not to be displayed below the `<input>`).

On top of that, is there a typo? the last-line `<del>` should be a `</del>` right?

Would is be possible to either get rid of the inner-div (the one after the
`<input>`) or give it its own class like `"task-content"`?

**Comment by smondet** [comment]
Also, it could be useful to have a CSS way of distinguishing between `` `Checked`` and all the `` `Other _`` for instance turning:

```markdown
- [🚧] hello
```

into something like:

```html
<input type="checkbox" disabled checked class="marker-x1f6a7"->
```

**Comment by dbuenzli** [comment]
Thanks for the `</del>` bug report.

I don't understand the rest of your request. [`<del>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del) is not an inline element it's flow content with a transparent content model, so it feels ok to replace the `div` by a `del`.

The inner `<div>`/`<del>` is here so that you can easily put the all the task content (which can be multiple blocks) next to the checkbox and align them on top (see [this rendering](https://github.com/dbuenzli/cmarkit/blob/main/test/expect/basic.exts.html) for example). No CSS "magic" is needed a simple [flex box](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) will do, see for example [here](https://github.com/dbuenzli/cmarkit/blob/abf7c375fa36b165c528944b3cc9cb20f5654f0c/tool/cmd_html.ml#L328-L331).

Regarding `` `Other`` I rather not do something that generic (also because no-one else does), it's also unclear what you could possibly do on a checkbox with that additional class. As written in the [docs](https://erratique.ch/software/cmarkit/doc/Cmarkit/index.html#ext_list_task_items) the default renderer equates it with `Checked`. If you want to do something else devise your own rendering for this case.

Closing but feel free to continue the discussion, if there's something I didn't get or if you disagree.
