### ISSUE TITLE
[bug] Default mapper throws away `Image` nodes with empty alt text `![](foo)`

### ISSUE THREAD

**Issue by nojb** [dbuenzli/cmarkit#6]
All image nodes of the form `![](foo)` are thrown away by the default mapper. For instance, the code
```ocaml
let () =
  let s = "![](foo)" in
  let doc = Cmarkit.Doc.of_string s in
  let doc = Cmarkit.Mapper.map_doc (Cmarkit.Mapper.make ()) doc in
  print_endline (Cmarkit_html.of_doc ~safe:false doc)
```
prints an empty string. The culprit is
https://github.com/dbuenzli/cmarkit/blob/c81369a2766baacb53fe790ebd82774864b17a76/src/cmarkit.ml#L3022-L3023
which throws away the `Image` node when `l.text` is empty. A fix could be:
```diff
diff --git a/src/cmarkit.ml b/src/cmarkit.ml
index cfa29e7..338c296 100644
--- a/src/cmarkit.ml
+++ b/src/cmarkit.ml
@@ -3019,7 +3019,11 @@ module Mapper = struct
       | Autolink _ | Break _ | Code_span _ | Raw_html _
       | Text _ | Ext_math_span _ as i -> Some i
       | Image (l, meta) ->
-          let* text = map_inline m l.text in
+          let text =
+            match map_inline m l.text with
+            | None -> (* Can be empty *) Inline.Inlines ([], Meta.none)
+            | Some i -> i
+          in
           Some (Image ({ l with text }, meta))
       | Link (l, meta) ->
           let* text = map_inline m l.text in
```

**Comment by dbuenzli** [comment]
That got me confused :-) I thought maybe deciding to map an empty `Inlines ([], _)` to `None` was the culprit. 

So in the [other cases] e.g. `Link` it's ok to throw away because that's actual element content so "it no longer exists". While in the `Image` case the content is the actual image not its link text ? 

I guess that makes sense.

[other cases]: https://github.com/dbuenzli/cmarkit/blob/c81369a2766baacb53fe790ebd82774864b17a76/src/cmarkit.ml#L3024-L3038

**Comment by nojb** [comment]
> While in the `Image` case the content is the actual image not its link text ?

That's my understanding!

**Comment by dbuenzli** [comment]
Thanks.
